wget -i links0.txt
wget -i links1.txt
wget -i links2.txt
wget -i links3.txt
wget -i links4.txt
wget -i links5.txt
wget -i links6.txt
wget -i links7.txt
wget -i links8.txt
wget -i links9.txt
wget -i links10.txt
wget -i links11.txt
wget -i links12.txt
wget -i links13.txt
wget -i links14.txt
wget -i links15.txt
wget -i links16.txt
wget -i links17.txt
wget -i links18.txt
wget -i links19.txt
wget -i links20.txt
wget -i links21.txt
wget -i links22.txt
wget -i links23.txt
wget -i links24.txt
wget -i links25.txt
wget -i links26.txt
wget -i links27.txt
wget -i links28.txt
wget -i links29.txt
wget -i links30.txt
wget -i links31.txt
wget -i links32.txt
wget -i links33.txt
wget -i links34.txt
wget -i links35.txt
wget -i links36.txt
wget -i links37.txt
wget -i links38.txt

